pipeline{
	agent any
	
	tools {
		maven "mvn"
	}
	stages {
		stage ('Build'){
			steps{
			
			// get code from github
			git url: 'https://github.com/akshaybade1313/Capstone_Project.git'
			
			script{
				if(isUnix()){
					sh "mvn clean install"
				}
				else{
					bat "mvn clean install"
				}
			}
			}
		}
		stage('Build Docker Image and Push Image To Hub'){
			steps{
			script{
				if(isUnix()){
					sh "docker buildx build . --platform linux/arm64 --tag akshaybade13/my-app:latest --push"
				}
				else{
					bat "docker buildx build . --platform linux/arm64 --tag akshaybade13/my-app:latest --push"
				}
			}
			}
		}
		stage('Deploy To Cloud'){
			steps{
			script{
				if(isUnix()){
					sh "kubectl apply -f deployment"
				}
				else{
					bat "kubectl apply -f deployment"
				}
			}
			}
		}
		
	}
	
}
